using Server.Models;

namespace Server.Services;

public class ImagePromptService
{
    public string BuildImagePrompt(Story story, StoryPage page)
    {
        // Build a distinct image prompt emphasizing cute, wholesome, vibrant cartoon style
        var themePart = string.IsNullOrWhiteSpace(story.Theme) ? string.Empty : $", theme: {story.Theme}";
        var childPart = $", main character is a {story.ChildAge} year old child";

        // Use the English image prompt generated by AI if available, otherwise fallback to simple scene description
        var visualDescription = !string.IsNullOrWhiteSpace(page.ImagePrompt) 
            ? page.ImagePrompt 
            : (page.Content?.Trim() ?? "A cute scene");

        // Strong negative prompting against text
        var prompt =
            $"Vibrant cartoon illustration, cute and wholesome, children's picture book, soft lighting, bright colors, high detail, 2D animation style, Ghibli-inspired, textless, no words, no letters, no typography, clear art, full scene{themePart}{childPart}. Visual: {visualDescription}";
        return prompt;
    }
}


